# kind: Secret
# apiVersion: v1
# metadata:
#   name: mongo-creds
# type: Opaque
# data:
#   password: YWRtaW4xMjMNCg==
#   username: cm9vdA0K

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-creds
   # Add the 'namespace' field here
type: Opaque
data:
  mysql-pass: ZW1hcnRkYnBhc3M=
  #rmq-pass: Z3Vlc3Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfig
     # Add the 'namespace' field here
data:
  # Configuration values can be set as key-value properties
  mongodbname: "epoc"
  mongo_uri: "mongodb://emongo:27017/epoc"
  mysqldbname: "books"
